### ISSUE TITLE
anonymous role when  RBAC_USE_WHITE = true  doesn't work

### ISSUE THREAD

**Issue by aurigadl** [shonenada/flask-rbac#11]
When the white list is placed as true, it don't make  successful validations for the anonymous role.
I'm not using flask-login, maybe this influence but I make the changes in the source code and now you can place the decorator @rbac.allow ([ 'anonymous'] methods = [ 'GET'], with_children = False) and working properly.

**Comment by trendsetter37** [comment]
@aurigadl what changes did you need to make to the source code?

**Comment by aurigadl** [comment]
Changes to the repository already been applied.
I needed to use the anonymous user, when the user was not logged.
[flask-rbac/commit](https://github.com/shonenada/flask-rbac/commit/d28486a32d4bfa8b79431b8a2bd982dd318f18f7)
