### ISSUE TITLE
 'RBAC' object has no attribute 'as_role_model'

### ISSUE THREAD

**Issue by aurigadl** [shonenada/flask-rbac#7]
The last version when I install with "`pip install flask-rbac`" the library does not have some method  like as_role_model, but  they are in the repository.

when I install with "`pip install git+https://github.com/shonenada/flask-rbac`" is all is well

Flask_RBAC-0.2.0-py2.7.egg-info
pip 1.5.6
Python 2.7.6

**Comment by rhymiz** [comment]
I confirm that this is also an issue on my end.

**Comment by shonenada** [comment]
Thank you for reporting this bug.
I have uploaded the new package to  Pypi. The new version number is `0.2.1`, please reinstall the new package, `pip install -U flask-rbac`.
