### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by rhymiz** [shonenada/flask-rbac#9]
There is a typo in the documentation. When setting multiple roles, the function name should be 'add_roles', as shown below.

`

    def add_role(self, role):
        self.roles.append(role)

    def add_roles(self, roles):
        for role in roles:
            self.add_role(role)

    def get_roles(self):
        for role in self.roles:
            yield role`

**Comment by shonenada** [comment]
Thanks, I have fixed it.
